# Franccesca

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'devops-franccesca'
    projectKey: 'DevOps-Franccesca_pet-clinic'
    projectName: 'pet-clinic'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false

- task: dependency-check-build-task@6
  inputs:
    projectName: 'pet-clinic'
    scanPath: '$(Build.SourcesDirectory)/build/libs'
    format: 'HTML'
    

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'devops-franccesca'

- stage: DAST
jobs:
- job: DAST
  steps:
    - script:
      docker pull owasp/zap2docker-stable
      docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://20.226.202.177:8085 -r DAST.html
      continueOnError: true
      displayName: DAST OWASP ZAP